---
- apt: name={{ item }} state=installed
  with_items:
    - runit
  when: ansible_os_family == 'Debian'

- file: path=/etc/tinc/{{ tinc_netname }}/hosts state=directory mode=0755 recurse=true
- shell: tincd -n {{ tinc_netname }} -K4096
  args:
    creates: "/etc/tinc/{{ tinc_netname }}/rsa_key.priv"

# Install the tinc package from repo if available
- apt: name=tinc state=installed
  when: ansible_os_family == 'Debian'

# Install the static binary if available
- unarchive: src=tinc-{{ ansible_architecture }}.tar.gz dest=/etc/tinc/ mode=0755
  when: tinc_static_binary

- file: path={{ tinc_tmpdir }}/{{ tinc_netname }}/pubkeys state=directory recurse=true 
  delegate_to: localhost
  sudo: false
- file: path={{ tinc_tmpdir }}/{{ tinc_netname }}/ip state=directory recurse=true 
  delegate_to: localhost
  sudo: false
- file: path={{ tinc_tmpdir }}/{{ tinc_netname }}/current state=directory recurse=true 
  delegate_to: localhost
  sudo: false

- fetch: src=/etc/tinc/{{ tinc_netname }}/ansible_ipaddress dest={{ tinc_tmpdir }}/{{ tinc_netname }}/ip/{{ ansible_hostname }} flat=yes
  ignore_errors: yes

- fetch: src=/etc/tinc/{{ tinc_netname }}/rsa_key.pub dest={{ tinc_tmpdir }}/{{ tinc_netname }}/pubkeys/{{ ansible_hostname }} flat=yes
  ignore_errors: yes

# Set an ipaddress for each host in set if they don't have already
- script: setip.py {{ tinc_tmpdir }}/{{ tinc_netname }}/pubkeys {{ tinc_tmpdir }}/{{ tinc_netname }}/ip {{ tinc_subnet }}
  tags: test
  register: ip_output
  delegate_to: localhost

- debug: var=ip_output
  tags: test

- template: src=host_configuration.j2 dest="{{ tinc_tmpdir }}/{{ tinc_netname }}/current/{{ ansible_hostname }}"
  tags: test
  delegate_to: localhost

- template: src=tinc.conf.j2 dest="/etc/tinc/{{ tinc_netname }}/tinc.conf" mode=0644
  notify: restart_tinc

- template: src=tinc-up.j2 dest="/etc/tinc/{{ tinc_netname }}/tinc-up" mode=0755
  notify: restart_tinc

- template: src=tinc-down.j2 dest="/etc/tinc/{{ tinc_netname }}/tinc-down" mode=0755
  notify: restart_tinc

- copy: src="{{ tinc_tmpdir}}/{{ tinc_netname }}/ip/{{ ansible_hostname }}" dest="/etc/tinc/{{ tinc_netname }}/ansible_ipaddress"

- copy: src="{{ tinc_tmpdir }}/{{ tinc_netname }}/current/" dest="/etc/tinc/{{ tinc_netname }}/hosts/"
  notify: restart_tinc

- lineinfile: dest="/etc/tinc/nets.boot" line="{{ tinc_netname }}" state=present
  notify: restart_tinc

# setup runit
- file: path=/etc/tinc/{{ tinc_netname }}/runit/log state=directory recurse=true
- file: path=/var/log/tinc_{{ tinc_netname }}/ state=directory mode=0755
- copy: dest="/etc/tinc/{{ tinc_netname }}/runit/run" mode=0755 content="#!/bin/sh\nexport PATH=/etc/tinc/bin:$PATH\nexec 2>&1\nexec tincd -n mesh -c /etc/tinc/mesh --pidfile=/etc/tinc/mesh/runit/pid -D"
  notify: restart_tinc
- copy: dest="/etc/tinc/{{ tinc_netname }}/runit/log/run" mode=0755 content="#!/bin/sh\nexec svlogd -tt /var/log/tinc_{{ tinc_netname }}"
  notify: restart_tinc
- file: src="/etc/tinc/{{ tinc_netname }}/runit" dest="/etc/service/tinc_{{ tinc_netname }}" state=link

# The facts aren't available on first run, so copy over all the ip addresses
- file: path=/etc/tinc/{{ tinc_netname }}/tmp state=directory mode=0755 recurse=true
- copy: src="{{ tinc_tmpdir}}/{{ tinc_netname }}/ip/" dest="/etc/tinc/{{ tinc_netname }}/tmp"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item | basename}}.{{ tinc_netname }}$' line="{{ lookup('file', item) }} {{ item | basename }}.{{ tinc_netname }}" state=present
  with_fileglob:
    - "/etc/tinc/{{ tinc_netname }}/tmp/*"
  tags: hostsfile

- file: dest="{{ tinc_tmpdir }}/{{ tinc_netname }}" state=absent
  delegate_to: localhost
  ignore_errors: yes
